ECHO  Переименовываем файлы для предприятия
MKDIR OK\
COPY PCB.GTL OK\TOP.GBR
COPY PCB.GBL OK\BOT.GBR
COPY PCB.GTS OK\TOPMASK.GBR
COPY PCB.GBS OK\BOTMASK.GBR
COPY PCB.GTO OK\TOPMARK.GBR
COPY PCB.GBO OK\BOTMARK.GBR
COPY PCB.GKO OK\BRDOUT.GBR
ECHO Готово